<a href="https://colab.research.google.com/github/younzk/rookie-projects/blob/main/%5BNumpy%5D%2002_Numpy_Data_Type.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#3.2 Numpy Data type

- 넘파이의 배열은 원소가 모두 같은 자료형이어야 한다.
- dtype 인수를 통해 자료형을 명시적으로 적용한다.
- dtype 인수가 없으면 dtype 속성을 통해 만들어진 배열의 자료형을 알아낸다.

In [ ]:
import numpy as np
x = np.array([1, 2, 3]) #정수형
y = np.array([1.0, 2.0, 3.0]) #실수형
x.dtype, y.dtype

(dtype('int64'), dtype('float64'))

dtype 인수로 지정할 자료형 종류  

![image.png]()

## Inf 와 NaN
- np.inf (infinity) - 무한대
- np.nan (not a number) - 정의할 수 없음

In [ ]:
np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.

array([  0.,  inf, -inf,  nan])

## 배열 생성
- zeros : 0으로 초기화 된 배열
- ones : 1로 초기화 된 배열
- zeros_like, ones_like : 이미 있는 배열과 같은 크기의 배열로 생성
- empty : 배열을 생성만 하고 특정 값으로 초기와 하지 않음.
- arange : NumPy 버전 range
- linspace, lognspace : 선형 구간 또는 로그 구간을 지정한 구간 수 만큼 분할한다.

In [ ]:
#크기가 정해져 있고 모든 값이 0인 배열을 생성

a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [ ]:
#크기를 나타내는 튜플로 다차원 배열 생성

b = np.zeros((2, 3))
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# dtype으로 해당 원소의 자료형을 지정할 수 있다.

c = np.zeros(5, dtype = "i")
c

array([0, 0, 0, 0, 0], dtype=int32)

In [ ]:
# 1로 초기화 된 배열 생성

e = np.ones((2, 3, 4), dtype = "i8") #3차원 배열 생성
e

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [ ]:
#zero_like, ones_like

f = np.ones_like(b, dtype = "f") #b는 (2, 3)크기를 가진 배열이었다.
f

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [ ]:
g = np.empty((4, 3))
g

array([[2.0347331e-316, 0.0000000e+000, 0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000, 0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000, 0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000, 0.0000000e+000]])

In [ ]:
np.arange(10) #0, 1, 2 .. 9

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(2, 10, 3) #(시작, 끝(포함X), 단계)

array([2, 5, 8])

In [ ]:
np.linspace(0, 100, 5) #시작, 끝, 구간 갯수

array([  0.,  25.,  50.,  75., 100.])

In [ ]:
np.logspace(0.1, 1, 10)

array([ 1.25892541,  1.58489319,  1.99526231,  2.51188643,  3.16227766,
        3.98107171,  5.01187234,  6.30957344,  7.94328235, 10.        ])

## Transpose (전치 연산)
- 행과 열을 바꾸는 작업
- T속성으로 구한다.

In [ ]:
A = np.array([[1, 2, 3], [4, 5, 6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

## Reshape (배열의 크기 변형)
- 배열 내부 데이터는 보존하고 형태만 바꾼다.
- 사용하는 원소의 개수가 정해져 있어서 reshape 명령 튜플 원소 중 하나는 -1로 대체할 수 있다.
- 다차원 배열을 1차원으로 만들기 위해서 flatten이나 ravel 메서드를 이용한다.
- 같은 배열에 대해 차원만 1차원 증가하는 경우는 newaxis를 이용한다.

In [ ]:
c = np.array([[1, 2, 3], [4, 5, 6]]) #2 x 3 array
c

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
d = c.reshape(3, 2) # 3 x 2 array
d

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
d = c.reshape(3, -1) # 튜플 원소 중 하나는 -1이라는 숫자로 대체할 수 있다.(자동으로 2로 생성됨)
d

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
d.flatten() #1차원으로 생성

array([1, 2, 3, 4, 5, 6])

In [ ]:
d.ravel() #1차원으로 생성

array([1, 2, 3, 4, 5, 6])

In [ ]:
d[:, np.newaxis] #같은 데이터를 갖고 있지만 3차원이 됨

array([[[1, 2]],

       [[3, 4]],

       [[5, 6]]])

## Concatenate (배열 연결)
- hstack : 행의 수(세로)가 같은 두 개 이상의 배열을 옆으로 연결, 연결할 배열은 하나의 리스트에 담는다.
- vstack : 열의 수(가로)가 같은 두 개 이상의 배열을 위 아래로 연결, 연결할 배열은 하나의 리스트에 담는다.
- dstack : 깊이(depth) 방향으로 배열, 가장 안쪽의 원소의 차원이 증가한다.
- stack : 사용자가 원하는 방향으로 차원을 증가시킨다.
- r_ : hstack과 비슷하게 배열을 좌우로 연결
- c_ : 배열의 차원 증가시킨 후 좌우로 연결, 만약 1차원 배열끼리 연결하면 2차원 배열이 된다.
- tile : 동일한 배열을 반복하여 연결

In [ ]:
#hstack
a1 = np.ones((2, 3))
a2 = np.zeros((2, 2))
np.hstack([a1, a2]) #a1, a2 배열을 하나의 리스트에 담아 hstack을 사용

array([[1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.]])

In [ ]:
#vstack
b1 = np.ones((2, 3))
b2 = np.zeros((3, 3))
np.vstack([b1, b2]) #a1, a2 배열을 하나의 리스트에 담아 vstack을 사용

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
#dstack
c1 = np.ones((3, 4))
c2 = np.zeros((3, 4))
np.dstack([c1, c2])

array([[[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]]])

In [ ]:
(np.dstack([c1, c2])).shape #c1, c2 모두 (3, 4) 크기의 배열이었는데 dstack 후 (3, 4, 2)로 가장 안쪽의 차원이 하나 증가했다.

(3, 4, 2)

In [ ]:
#stack axis = 0일 때 (3, 4) -> (2, 3, 4)로 첫 번째 차원이 증가
c = np.stack([c1, c2])
c

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
#stack axis = 1일 때 (3, 4) -> (3, 2, 4)로 두 번째 차원이 증가
c = np.stack([c1, c2], axis = 1)
c

array([[[1., 1., 1., 1.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [0., 0., 0., 0.]]])

In [ ]:
#stack axis = 2일 때 (3, 4) -> (3, 4, 2)로 두 번째 차원이 증가 = dstack과 동일
c = np.stack([c1, c2], axis = 2)
c

array([[[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]]])

In [ ]:
#r_ 메서드 = hstack과 비슷하게 배열을 좌우로 연결
np.r_[np.array([1, 2, 3]), np.array([4, 5, 6])]

array([1, 2, 3, 4, 5, 6])

In [ ]:
#c_ 메서드 = 배열의 차원 증가시킨 후 좌우로 연결 
np.c_[np.array([1, 2, 3]), np.array([4, 5, 6])]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
a = np.array([[0, 1, 2], [3, 4, 5]])
np.tile(a, 2) #a를 2번 연결

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [ ]:
a = np.array([[0, 1, 2], [3, 4, 5]])
np.tile(a, (3, 2)) #a를 2번 연결

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

### Practice 01
- 다음 배열을 만들어 보시오.

array([[   0.,    0.,    0.,    1.,    1.],  
       [   0.,    0.,    0.,    1.,    1.],  
       [   0.,    0.,    0.,    1.,    1.],  
       [  10.,   20.,   30.,   40.,   50.],  
       [  60.,   70.,   80.,   90.,  100.],  
       [ 110.,  120.,  130.,  140.,  150.],  
       [   0.,    0.,    0.,    1.,    1.],  
       [   0.,    0.,    0.,    1.,    1.],  
       [   0.,    0.,    0.,    1.,    1.],  
       [  10.,   20.,   30.,   40.,   50.],  
       [  60.,   70.,   80.,   90.,  100.],  
       [ 110.,  120.,  130.,  140.,  150.]])

In [ ]:
a0 = np.zeros(3)
a1 = np.ones(2)
a = np.hstack([a0, a1])
a = np.vstack([a, a, a])
a

array([[0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 1.]])

In [ ]:
b0 = np.arange(10, 160, 10)
b = b0.reshape(3, 5)

In [ ]:
c = np.vstack([a, b])
c

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

In [ ]:
np.tile(c, (2, 1))

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

## 2차원 그리드 포인트 생성
- 그리드 포인트(grid point) : 변수가 2개인 2차원 함수의 그래프에서(x, y) 좌표값의 쌍
- meshgrid : 사각형 영역을 구성하는 가로축의 점들과 세로축의 점들을 나타내는 두 벡터를 인수로 받아 사각형 영역을 이루는 조합을 출력한다.

In [ ]:
x = np.arange(3)
x

array([0, 1, 2])

In [ ]:
y = np.arange(5)
y

array([0, 1, 2, 3, 4])

In [ ]:
X, Y = np.meshgrid(x, y)

In [ ]:
X

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [ ]:
Y

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

In [ ]:
#그리드 포인트를 (X, Y) 값으로 출력
[list(zip(x, y)) for x, y in zip(X, Y)]

[[(0, 0), (1, 0), (2, 0)],
 [(0, 1), (1, 1), (2, 1)],
 [(0, 2), (1, 2), (2, 2)],
 [(0, 3), (1, 3), (2, 3)],
 [(0, 4), (1, 4), (2, 4)]]